PRODUCT_COPY_FILES += \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/imscmservice:system/bin/imscmservice \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/imsdatadaemon:system/bin/imsdatadaemon \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/imsqmidaemon:system/bin/imsqmidaemon \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/ims_rtp_daemon:system/bin/ims_rtp_daemon \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/loc_launcher:system/bin/loc_launcher \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/lowi-server:system/bin/lowi-server \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/radish:system/bin/radish \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/vm_bms:system/bin/vm_bms \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/xtwifi-client:system/bin/xtwifi-client \
    vendor/asus/ASUS_X00AD_2/proprietary/bin/xtwifi-inet-agent:system/bin/xtwifi-inet-agent \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/flp.conf:system/etc/flp.conf \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/izat.conf:system/etc/izat.conf \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/lowi.conf:system/etc/lowi.conf \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/permissions/com.qti.location.sdk.xml:system/etc/permissions/com.qti.location.sdk.xml \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/permissions/imscm.xml:system/etc/permissions/imscm.xml \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/sap.conf:system/etc/sap.conf \
    vendor/asus/ASUS_X00AD_2/proprietary/etc/xtwifi.conf:system/etc/xtwifi.conf \
    vendor/asus/ASUS_X00AD_2/proprietary/lib64/hw/gps.default.so:system/lib64/hw/gps.default.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib64/hw/lights.msm8916.so:system/lib64/hw/lights.msm8916.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib64/hw/sensors.msm8916.so:system/lib64/hw/sensors.msm8916.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib64/libgps.utils.so:system/lib64/libgps.utils.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib64/libloc_api_v02.so:system/lib64/libloc_api_v02.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib64/libloc_core.so:system/lib64/libloc_core.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib64/libloc_eng.so:system/lib64/libloc_eng.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/hw/camera.msm8916.so:system/lib/hw/camera.msm8916.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/hw/lights.msm8916.so:system/lib/hw/lights.msm8916.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/hw/sensors.msm8916.so:system/lib/hw/sensors.msm8916.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libaptX-1.0.0-rel-Android21-ARMv7A.so:system/lib/libaptX-1.0.0-rel-Android21-ARMv7A.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libaptXHD-1.0.0-rel-Android21-ARMv7A.so:system/lib/libaptXHD-1.0.0-rel-Android21-ARMv7A.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libaptXScheduler.so:system/lib/libaptXScheduler.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libarcsoft_beautyshot.so:system/lib/libarcsoft_beautyshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libarcsoft_face_tracking.so:system/lib/libarcsoft_face_tracking.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libarcsoft_hdr.so:system/lib/libarcsoft_hdr.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libarcsoft_panorama_burstcapture.so:system/lib/libarcsoft_panorama_burstcapture.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libcameraap.so:system/lib/libcameraap.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libcamera_defocus.so:system/lib/libcamera_defocus.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libcamera_pano.so:system/lib/libcamera_pano.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libjpeggifcodec.so:system/lib/libjpeggifcodec.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libloc_core.so:system/lib/libloc_core.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libmorpho_panorama_gp.so:system/lib/libmorpho_panorama_gp.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libmpbase.so:system/lib/libmpbase.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libOmxVdecHevc.so:system/lib/libOmxVdecHevc.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libsarcsoftface.so:system/lib/libsarcsoftface.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libsarcsoft_gallery.so:system/lib/libsarcsoft_gallery.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/libsphere3.so:system/lib/libsphere3.so \
    vendor/asus/ASUS_X00AD_2/proprietary/lib/style.cng:system/lib/style.cng \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/bin/perfd:system/vendor/bin/perfd \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/etc/style.cng:system/vendor/etc/style.cng \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/egl/eglsubAndroid.so:system/vendor/lib64/egl/eglsubAndroid.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/egl/eglSubDriverAndroid.so:system/vendor/lib64/egl/eglSubDriverAndroid.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/egl/libEGL_adreno.so:system/vendor/lib64/egl/libEGL_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/egl/libESXEGL_adreno.so:system/vendor/lib64/egl/libESXEGL_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib64/egl/libESXGLESv1_CM_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/egl/libESXGLESv2_adreno.so:system/vendor/lib64/egl/libESXGLESv2_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/egl/libGLESv1_CM_adreno.so:system/vendor/lib64/egl/libGLESv1_CM_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/egl/libGLESv2_adreno.so:system/vendor/lib64/egl/libGLESv2_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/egl/libq3dtools_adreno.so:system/vendor/lib64/egl/libq3dtools_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/egl/libQTapGLES.so:system/vendor/lib64/egl/libQTapGLES.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/egl/libRBEGL_adreno.so:system/vendor/lib64/egl/libRBEGL_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib64/egl/libRBGLESv1_CM_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/egl/libRBGLESv2_adreno.so:system/vendor/lib64/egl/libRBGLESv2_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/hw/flp.default.so:system/vendor/lib64/hw/flp.default.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libacdb-fts.so:system/vendor/lib64/libacdb-fts.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libacdbloader.so:system/vendor/lib64/libacdbloader.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libacdbrtac.so:system/vendor/lib64/libacdbrtac.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libadiertac.so:system/vendor/lib64/libadiertac.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libadreno_utils.so:system/vendor/lib64/libadreno_utils.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libadsprpc.so:system/vendor/lib64/libadsprpc.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libalarmservice_jni.so:system/vendor/lib64/libalarmservice_jni.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libasn1cper.so:system/vendor/lib64/libasn1cper.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libasn1crt.so:system/vendor/lib64/libasn1crt.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libasn1crtx.so:system/vendor/lib64/libasn1crtx.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libaudcal.so:system/vendor/lib64/libaudcal.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libbtnv.so:system/vendor/lib64/libbtnv.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libC2D2.so:system/vendor/lib64/libC2D2.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libc2d30-a3xx.so:system/vendor/lib64/libc2d30-a3xx.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libc2d30-a4xx.so:system/vendor/lib64/libc2d30-a4xx.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libCB.so:system/vendor/lib64/libCB.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_imx135_liveshot.so:system/vendor/lib64/libchromatix_imx135_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_imx214_common.so:system/vendor/lib64/libchromatix_imx214_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_imx214_default_video.so:system/vendor/lib64/libchromatix_imx214_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_imx214_hfr_120fps.so:system/vendor/lib64/libchromatix_imx214_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_imx214_hfr_60fps.so:system/vendor/lib64/libchromatix_imx214_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_imx214_hfr_90fps.so:system/vendor/lib64/libchromatix_imx214_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_imx214_liveshot.so:system/vendor/lib64/libchromatix_imx214_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_imx214_preview.so:system/vendor/lib64/libchromatix_imx214_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_imx214_snapshot_hdr.so:system/vendor/lib64/libchromatix_imx214_snapshot_hdr.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_imx214_snapshot.so:system/vendor/lib64/libchromatix_imx214_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_imx214_video_1080p.so:system/vendor/lib64/libchromatix_imx214_video_1080p.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_imx214_video_hdr.so:system/vendor/lib64/libchromatix_imx214_video_hdr.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov13850_default_video.so:system/vendor/lib64/libchromatix_ov13850_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov13850_q13v06k_default_video.so:system/vendor/lib64/libchromatix_ov13850_q13v06k_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov16825_common.so:system/vendor/lib64/libchromatix_ov16825_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov16825_default_video.so:system/vendor/lib64/libchromatix_ov16825_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov16825_preview.so:system/vendor/lib64/libchromatix_ov16825_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov16825_snapshot.so:system/vendor/lib64/libchromatix_ov16825_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_common.so:system/vendor/lib64/libchromatix_ov8858_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_default_video.so:system/vendor/lib64/libchromatix_ov8858_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_hfr_120fps.so:system/vendor/lib64/libchromatix_ov8858_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_hfr_60fps.so:system/vendor/lib64/libchromatix_ov8858_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_hfr_90fps.so:system/vendor/lib64/libchromatix_ov8858_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_liveshot.so:system/vendor/lib64/libchromatix_ov8858_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_preview.so:system/vendor/lib64/libchromatix_ov8858_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_common.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_default_video.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_120fps.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_60fps.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_90fps.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_liveshot.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_preview.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_snapshot.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_video_nonHD.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_video_nonHD.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_zsl_30.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_zsl_30.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_zsl.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_ov8858_snapshot.so:system/vendor/lib64/libchromatix_ov8858_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_s5k3m2xm_common.so:system/vendor/lib64/libchromatix_s5k3m2xm_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_s5k3m2xm_default_video.so:system/vendor/lib64/libchromatix_s5k3m2xm_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_s5k3m2xm_liveshot.so:system/vendor/lib64/libchromatix_s5k3m2xm_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_s5k3m2xm_preview.so:system/vendor/lib64/libchromatix_s5k3m2xm_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libchromatix_s5k3m2xm_snapshot.so:system/vendor/lib64/libchromatix_s5k3m2xm_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libcneapiclient.so:system/vendor/lib64/libcneapiclient.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libdataitems.so:system/vendor/lib64/libdataitems.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libdisp-aba.so:system/vendor/lib64/libdisp-aba.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-dplmedia.so:system/vendor/lib64/lib-dplmedia.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libdrmfs.so:system/vendor/lib64/libdrmfs.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libdrmtime.so:system/vendor/lib64/libdrmtime.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libFlacSwDec.so:system/vendor/lib64/libFlacSwDec.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libflp.so:system/vendor/lib64/libflp.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libgdtap.so:system/vendor/lib64/libgdtap.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libgeofence.so:system/vendor/lib64/libgeofence.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libgsl.so:system/vendor/lib64/libgsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libimscamera_jni.so:system/vendor/lib64/libimscamera_jni.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-imscamera.so:system/vendor/lib64/lib-imscamera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-imsdpl.so:system/vendor/lib64/lib-imsdpl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libimsmedia_jni.so:system/vendor/lib64/libimsmedia_jni.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-imsqimf.so:system/vendor/lib64/lib-imsqimf.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-imsrcscmclient.so:system/vendor/lib64/lib-imsrcscmclient.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-ims-rcscmjni.so:system/vendor/lib64/lib-ims-rcscmjni.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-imsrcscmservice.so:system/vendor/lib64/lib-imsrcscmservice.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-imsrcscm.so:system/vendor/lib64/lib-imsrcscm.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-imsrcs.so:system/vendor/lib64/lib-imsrcs.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-imsSDP.so:system/vendor/lib64/lib-imsSDP.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-imss.so:system/vendor/lib64/lib-imss.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-imsvt.so:system/vendor/lib64/lib-imsvt.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-imsxml.so:system/vendor/lib64/lib-imsxml.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libizat_core.so:system/vendor/lib64/libizat_core.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/liblbs_core.so:system/vendor/lib64/liblbs_core.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libllvm-glnext.so:system/vendor/lib64/libllvm-glnext.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libllvm-qcom.so:system/vendor/lib64/libllvm-qcom.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/liblocationservice_glue.so:system/vendor/lib64/liblocationservice_glue.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/liblocationservice.so:system/vendor/lib64/liblocationservice.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libloc_ext.so:system/vendor/lib64/libloc_ext.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libloc_xtra.so:system/vendor/lib64/libloc_xtra.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/liblowi_client.so:system/vendor/lib64/liblowi_client.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/liblowi_wifihal_nl.so:system/vendor/lib64/liblowi_wifihal_nl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/liblowi_wifihal.so:system/vendor/lib64/liblowi_wifihal.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/liblqe.so:system/vendor/lib64/liblqe.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libmm-abl-oem.so:system/vendor/lib64/libmm-abl-oem.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libmm-abl.so:system/vendor/lib64/libmm-abl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libmmcamera2_frame_algorithm.so:system/vendor/lib64/libmmcamera2_frame_algorithm.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libmmcamera2_q3a_core.so:system/vendor/lib64/libmmcamera2_q3a_core.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libmmcamera2_stats_algorithm.so:system/vendor/lib64/libmmcamera2_stats_algorithm.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libmmcamera_imx214.so:system/vendor/lib64/libmmcamera_imx214.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libmmcamera_ov16825.so:system/vendor/lib64/libmmcamera_ov16825.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libmmcamera_ov7695.so:system/vendor/lib64/libmmcamera_ov7695.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libmmcamera_ov8858_q8v19w_30.so:system/vendor/lib64/libmmcamera_ov8858_q8v19w_30.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libmmcamera_ov8858_q8v19w.so:system/vendor/lib64/libmmcamera_ov8858_q8v19w.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libmmcamera_ov8858.so:system/vendor/lib64/libmmcamera_ov8858.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libmm-disp-apis.so:system/vendor/lib64/libmm-disp-apis.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libmm-qdcm.so:system/vendor/lib64/libmm-qdcm.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libOpenCL.so:system/vendor/lib64/libOpenCL.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libperipheral_client.so:system/vendor/lib64/libperipheral_client.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libqcci_legacy.so:system/vendor/lib64/libqcci_legacy.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libqdp.so:system/vendor/lib64/libqdp.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libqmi_client_helper.so:system/vendor/lib64/libqmi_client_helper.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libQSEEComAPI.so:system/vendor/lib64/libQSEEComAPI.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libqti-perfd-client.so:system/vendor/lib64/libqti-perfd-client.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libquipc_os_api.so:system/vendor/lib64/libquipc_os_api.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-rcsimssjni.so:system/vendor/lib64/lib-rcsimssjni.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-rcsjni.so:system/vendor/lib64/lib-rcsjni.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libril-qc-qmi-1.so:system/vendor/lib64/libril-qc-qmi-1.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libril-qc-radioconfig.so:system/vendor/lib64/libril-qc-radioconfig.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/librpmb.so:system/vendor/lib64/librpmb.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/librs_adreno_sha1.so:system/vendor/lib64/librs_adreno_sha1.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/librs_adreno.so:system/vendor/lib64/librs_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libRSDriver_adreno.so:system/vendor/lib64/libRSDriver_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-rtpcommon.so:system/vendor/lib64/lib-rtpcommon.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-rtpcore.so:system/vendor/lib64/lib-rtpcore.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-rtpdaemoninterface.so:system/vendor/lib64/lib-rtpdaemoninterface.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/lib-rtpsl.so:system/vendor/lib64/lib-rtpsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libsc-a3xx.so:system/vendor/lib64/libsc-a3xx.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libscale.so:system/vendor/lib64/libscale.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libssd.so:system/vendor/lib64/libssd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libthermalclient.so:system/vendor/lib64/libthermalclient.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libthermalioctl.so:system/vendor/lib64/libthermalioctl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libTimeService.so:system/vendor/lib64/libTimeService.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libulp2.so:system/vendor/lib64/libulp2.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libvcel.so:system/vendor/lib64/libvcel.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libvoice-svc.so:system/vendor/lib64/libvoice-svc.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libxtadapter.so:system/vendor/lib64/libxtadapter.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libxt_native.so:system/vendor/lib64/libxt_native.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib64/libxtwifi_ulp_adaptor.so:system/vendor/lib64/libxtwifi_ulp_adaptor.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/egl/libESXEGL_adreno.so:system/vendor/lib/egl/libESXEGL_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib/egl/libESXGLESv1_CM_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/egl/libESXGLESv2_adreno.so:system/vendor/lib/egl/libESXGLESv2_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/egl/libRBEGL_adreno.so:system/vendor/lib/egl/libRBEGL_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib/egl/libRBGLESv1_CM_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/egl/libRBGLESv2_adreno.so:system/vendor/lib/egl/libRBGLESv2_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_a3907_camcorder.so:system/vendor/lib/libactuator_a3907_camcorder.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_a3907_camera.so:system/vendor/lib/libactuator_a3907_camera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_a3907.so:system/vendor/lib/libactuator_a3907.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_bu64297_q13v06k_camcorder.so:system/vendor/lib/libactuator_bu64297_q13v06k_camcorder.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_bu64297_q13v06k_camera.so:system/vendor/lib/libactuator_bu64297_q13v06k_camera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_bu64297_q13v06k.so:system/vendor/lib/libactuator_bu64297_q13v06k.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so:system/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_13p1ba_camera.so:system/vendor/lib/libactuator_dw9714_13p1ba_camera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_13p1ba.so:system/vendor/lib/libactuator_dw9714_13p1ba.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_camcorder.so:system/vendor/lib/libactuator_dw9714_camcorder.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_camera.so:system/vendor/lib/libactuator_dw9714_camera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_pc0fe_camcorder.so:system/vendor/lib/libactuator_dw9714_pc0fe_camcorder.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_pc0fe_camera.so:system/vendor/lib/libactuator_dw9714_pc0fe_camera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_pc0fe.so:system/vendor/lib/libactuator_dw9714_pc0fe.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_q13n04a_camcorder.so:system/vendor/lib/libactuator_dw9714_q13n04a_camcorder.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_q13n04a_camera.so:system/vendor/lib/libactuator_dw9714_q13n04a_camera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_q13n04a.so:system/vendor/lib/libactuator_dw9714_q13n04a.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_q13v04b_camcorder.so:system/vendor/lib/libactuator_dw9714_q13v04b_camcorder.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_q13v04b_camera.so:system/vendor/lib/libactuator_dw9714_q13v04b_camera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_q13v04b.so:system/vendor/lib/libactuator_dw9714_q13v04b.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_q8v19w_camcorder.so:system/vendor/lib/libactuator_dw9714_q8v19w_camcorder.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_q8v19w_camera.so:system/vendor/lib/libactuator_dw9714_q8v19w_camera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_q8v19w.so:system/vendor/lib/libactuator_dw9714_q8v19w.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_qtech_camcorder.so:system/vendor/lib/libactuator_dw9714_qtech_camcorder.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_qtech_camera.so:system/vendor/lib/libactuator_dw9714_qtech_camera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714_qtech.so:system/vendor/lib/libactuator_dw9714_qtech.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9714.so:system/vendor/lib/libactuator_dw9714.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9716_camcorder.so:system/vendor/lib/libactuator_dw9716_camcorder.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9716_camera.so:system/vendor/lib/libactuator_dw9716_camera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9716.so:system/vendor/lib/libactuator_dw9716.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9761b_camcorder.so:system/vendor/lib/libactuator_dw9761b_camcorder.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9761b_camera.so:system/vendor/lib/libactuator_dw9761b_camera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_dw9761b.so:system/vendor/lib/libactuator_dw9761b.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_iu074_camcorder.so:system/vendor/lib/libactuator_iu074_camcorder.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_iu074_camera.so:system/vendor/lib/libactuator_iu074_camera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_iu074.so:system/vendor/lib/libactuator_iu074.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_ov12830_camcorder.so:system/vendor/lib/libactuator_ov12830_camcorder.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_ov12830_camera.so:system/vendor/lib/libactuator_ov12830_camera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_ov12830.so:system/vendor/lib/libactuator_ov12830.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_ov8825_camcorder.so:system/vendor/lib/libactuator_ov8825_camcorder.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_ov8825_camera.so:system/vendor/lib/libactuator_ov8825_camera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_ov8825.so:system/vendor/lib/libactuator_ov8825.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_camera.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libactuator_rohm_bu64243gwz.so:system/vendor/lib/libactuator_rohm_bu64243gwz.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libarcsoft_night_shot.so:system/vendor/lib/libarcsoft_night_shot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx132_common.so:system/vendor/lib/libchromatix_imx132_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx132_default_video.so:system/vendor/lib/libchromatix_imx132_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx132_liveshot.so:system/vendor/lib/libchromatix_imx132_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx132_preview.so:system/vendor/lib/libchromatix_imx132_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx132_snapshot.so:system/vendor/lib/libchromatix_imx132_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx134_common.so:system/vendor/lib/libchromatix_imx134_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx134_default_video.so:system/vendor/lib/libchromatix_imx134_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx134_hfr_120.so:system/vendor/lib/libchromatix_imx134_hfr_120.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx134_hfr_60.so:system/vendor/lib/libchromatix_imx134_hfr_60.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx134_preview.so:system/vendor/lib/libchromatix_imx134_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx134_snapshot.so:system/vendor/lib/libchromatix_imx134_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx135_adrc.so:system/vendor/lib/libchromatix_imx135_adrc.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx135_common.so:system/vendor/lib/libchromatix_imx135_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx135_default_video.so:system/vendor/lib/libchromatix_imx135_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx135_hfr_120.so:system/vendor/lib/libchromatix_imx135_hfr_120.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx135_hfr_60.so:system/vendor/lib/libchromatix_imx135_hfr_60.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx135_hfr_90.so:system/vendor/lib/libchromatix_imx135_hfr_90.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx135_liveshot.so:system/vendor/lib/libchromatix_imx135_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx135_preview.so:system/vendor/lib/libchromatix_imx135_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx135_snapshot.so:system/vendor/lib/libchromatix_imx135_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx135_video_hd.so:system/vendor/lib/libchromatix_imx135_video_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx214_common.so:system/vendor/lib/libchromatix_imx214_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx214_default_video.so:system/vendor/lib/libchromatix_imx214_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx214_hfr_120fps.so:system/vendor/lib/libchromatix_imx214_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx214_hfr_60fps.so:system/vendor/lib/libchromatix_imx214_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx214_hfr_90fps.so:system/vendor/lib/libchromatix_imx214_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx214_liveshot.so:system/vendor/lib/libchromatix_imx214_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx214_preview.so:system/vendor/lib/libchromatix_imx214_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx214_snapshot_hdr.so:system/vendor/lib/libchromatix_imx214_snapshot_hdr.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx214_snapshot.so:system/vendor/lib/libchromatix_imx214_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx214_video_1080p.so:system/vendor/lib/libchromatix_imx214_video_1080p.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_imx214_video_hdr.so:system/vendor/lib/libchromatix_imx214_video_hdr.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov13850_common.so:system/vendor/lib/libchromatix_ov13850_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov13850_default_video.so:system/vendor/lib/libchromatix_ov13850_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov13850_hfr_120fps.so:system/vendor/lib/libchromatix_ov13850_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov13850_hfr_60fps.so:system/vendor/lib/libchromatix_ov13850_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov13850_hfr_90fps.so:system/vendor/lib/libchromatix_ov13850_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov13850_preview.so:system/vendor/lib/libchromatix_ov13850_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov13850_q13v06k_common.so:system/vendor/lib/libchromatix_ov13850_q13v06k_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov13850_q13v06k_default_video.so:system/vendor/lib/libchromatix_ov13850_q13v06k_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov13850_q13v06k_hfr_120fps.so:system/vendor/lib/libchromatix_ov13850_q13v06k_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov13850_q13v06k_hfr_60fps.so:system/vendor/lib/libchromatix_ov13850_q13v06k_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov13850_q13v06k_hfr_90fps.so:system/vendor/lib/libchromatix_ov13850_q13v06k_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov13850_q13v06k_preview.so:system/vendor/lib/libchromatix_ov13850_q13v06k_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov13850_q13v06k_snapshot.so:system/vendor/lib/libchromatix_ov13850_q13v06k_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov13850_snapshot.so:system/vendor/lib/libchromatix_ov13850_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov16825_common.so:system/vendor/lib/libchromatix_ov16825_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov16825_default_video.so:system/vendor/lib/libchromatix_ov16825_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov16825_preview.so:system/vendor/lib/libchromatix_ov16825_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov16825_snapshot.so:system/vendor/lib/libchromatix_ov16825_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_common.so:system/vendor/lib/libchromatix_ov2680_5987fhq_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_common_v32.so:system/vendor/lib/libchromatix_ov2680_5987fhq_common_v32.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_default_video.so:system/vendor/lib/libchromatix_ov2680_5987fhq_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_default_video_v32.so:system/vendor/lib/libchromatix_ov2680_5987fhq_default_video_v32.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_preview.so:system/vendor/lib/libchromatix_ov2680_5987fhq_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_preview_v32.so:system/vendor/lib/libchromatix_ov2680_5987fhq_preview_v32.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_snapshot.so:system/vendor/lib/libchromatix_ov2680_5987fhq_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_snapshot_v32.so:system/vendor/lib/libchromatix_ov2680_5987fhq_snapshot_v32.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_cht852b_common.so:system/vendor/lib/libchromatix_ov2680_cht852b_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_cht852b_default_video.so:system/vendor/lib/libchromatix_ov2680_cht852b_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_cht852b_preview.so:system/vendor/lib/libchromatix_ov2680_cht852b_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_cht852b_snapshot.so:system/vendor/lib/libchromatix_ov2680_cht852b_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_common.so:system/vendor/lib/libchromatix_ov2680_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_default_video.so:system/vendor/lib/libchromatix_ov2680_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_preview.so:system/vendor/lib/libchromatix_ov2680_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_snapshot.so:system/vendor/lib/libchromatix_ov2680_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_zs2p80f1_common.so:system/vendor/lib/libchromatix_ov2680_zs2p80f1_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_zs2p80f1_default_video.so:system/vendor/lib/libchromatix_ov2680_zs2p80f1_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_zs2p80f1_preview.so:system/vendor/lib/libchromatix_ov2680_zs2p80f1_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2680_zs2p80f1_snapshot.so:system/vendor/lib/libchromatix_ov2680_zs2p80f1_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2720_common.so:system/vendor/lib/libchromatix_ov2720_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2720_default_video.so:system/vendor/lib/libchromatix_ov2720_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2720_hfr.so:system/vendor/lib/libchromatix_ov2720_hfr.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2720_liveshot.so:system/vendor/lib/libchromatix_ov2720_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2720_preview.so:system/vendor/lib/libchromatix_ov2720_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov2720_zsl.so:system/vendor/lib/libchromatix_ov2720_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_common.so:system/vendor/lib/libchromatix_ov5648_oty5f03_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so:system/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_preview.so:system/vendor/lib/libchromatix_ov5648_oty5f03_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so:system/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so:system/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5648_p5v18g_common.so:system/vendor/lib/libchromatix_ov5648_p5v18g_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5648_p5v18g_default_video_hd.so:system/vendor/lib/libchromatix_ov5648_p5v18g_default_video_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5648_p5v18g_default_video.so:system/vendor/lib/libchromatix_ov5648_p5v18g_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5648_p5v18g_preview.so:system/vendor/lib/libchromatix_ov5648_p5v18g_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5648_p5v18g_snapshot.so:system/vendor/lib/libchromatix_ov5648_p5v18g_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5648_p5v18g_zsl.so:system/vendor/lib/libchromatix_ov5648_p5v18g_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_common.so:system/vendor/lib/libchromatix_ov5648_q5v22e_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_default_video_hd.so:system/vendor/lib/libchromatix_ov5648_q5v22e_default_video_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_default_video.so:system/vendor/lib/libchromatix_ov5648_q5v22e_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_preview.so:system/vendor/lib/libchromatix_ov5648_q5v22e_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_snapshot.so:system/vendor/lib/libchromatix_ov5648_q5v22e_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_zsl.so:system/vendor/lib/libchromatix_ov5648_q5v22e_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_30010a3_common.so:system/vendor/lib/libchromatix_ov5670_30010a3_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_30010a3_default_video.so:system/vendor/lib/libchromatix_ov5670_30010a3_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_30010a3_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_30010a3_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_30010a3_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_30010a3_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_30010a3_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_30010a3_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_30010a3_liveshot.so:system/vendor/lib/libchromatix_ov5670_30010a3_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_30010a3_preview.so:system/vendor/lib/libchromatix_ov5670_30010a3_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_30010a3_snapshot.so:system/vendor/lib/libchromatix_ov5670_30010a3_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_30010a3_video_hd.so:system/vendor/lib/libchromatix_ov5670_30010a3_video_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_30010a3_zsl.so:system/vendor/lib/libchromatix_ov5670_30010a3_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_common.so:system/vendor/lib/libchromatix_ov5670_q5v41b_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_default_video.so:system/vendor/lib/libchromatix_ov5670_q5v41b_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_liveshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_preview.so:system/vendor/lib/libchromatix_ov5670_q5v41b_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_snapshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_video_hd.so:system/vendor/lib/libchromatix_ov5670_q5v41b_video_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_zsl.so:system/vendor/lib/libchromatix_ov5670_q5v41b_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_qc700_common.so:system/vendor/lib/libchromatix_ov5670_qc700_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_qc700_default_video.so:system/vendor/lib/libchromatix_ov5670_qc700_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_qc700_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_qc700_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_qc700_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_qc700_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_qc700_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_qc700_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_qc700_liveshot.so:system/vendor/lib/libchromatix_ov5670_qc700_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_qc700_preview.so:system/vendor/lib/libchromatix_ov5670_qc700_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_qc700_snapshot.so:system/vendor/lib/libchromatix_ov5670_qc700_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_qc700_video_hd.so:system/vendor/lib/libchromatix_ov5670_qc700_video_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov5670_qc700_zsl.so:system/vendor/lib/libchromatix_ov5670_qc700_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8825_common.so:system/vendor/lib/libchromatix_ov8825_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8825_default_video.so:system/vendor/lib/libchromatix_ov8825_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8825_hfr_120fps.so:system/vendor/lib/libchromatix_ov8825_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8825_hfr_60fps.so:system/vendor/lib/libchromatix_ov8825_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8825_hfr_90fps.so:system/vendor/lib/libchromatix_ov8825_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8825_liveshot_hd.so:system/vendor/lib/libchromatix_ov8825_liveshot_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8825_liveshot.so:system/vendor/lib/libchromatix_ov8825_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8825_preview_hd.so:system/vendor/lib/libchromatix_ov8825_preview_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8825_preview.so:system/vendor/lib/libchromatix_ov8825_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8825_snapshot_hd.so:system/vendor/lib/libchromatix_ov8825_snapshot_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8825_snapshot.so:system/vendor/lib/libchromatix_ov8825_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8825_video_hd.so:system/vendor/lib/libchromatix_ov8825_video_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8825_zsl.so:system/vendor/lib/libchromatix_ov8825_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_common.so:system/vendor/lib/libchromatix_ov8858_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_default_video.so:system/vendor/lib/libchromatix_ov8858_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_hfr_120fps.so:system/vendor/lib/libchromatix_ov8858_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_hfr_60fps.so:system/vendor/lib/libchromatix_ov8858_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_hfr_90fps.so:system/vendor/lib/libchromatix_ov8858_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_liveshot.so:system/vendor/lib/libchromatix_ov8858_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_preview.so:system/vendor/lib/libchromatix_ov8858_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_common.so:system/vendor/lib/libchromatix_ov8858_q8v19w_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_default_video.so:system/vendor/lib/libchromatix_ov8858_q8v19w_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_hfr_120fps.so:system/vendor/lib/libchromatix_ov8858_q8v19w_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_hfr_60fps.so:system/vendor/lib/libchromatix_ov8858_q8v19w_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_hfr_90fps.so:system/vendor/lib/libchromatix_ov8858_q8v19w_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_liveshot.so:system/vendor/lib/libchromatix_ov8858_q8v19w_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_preview.so:system/vendor/lib/libchromatix_ov8858_q8v19w_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_snapshot.so:system/vendor/lib/libchromatix_ov8858_q8v19w_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_video_nonHD.so:system/vendor/lib/libchromatix_ov8858_q8v19w_video_nonHD.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_zsl_30.so:system/vendor/lib/libchromatix_ov8858_q8v19w_zsl_30.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_zsl.so:system/vendor/lib/libchromatix_ov8858_q8v19w_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8858_snapshot.so:system/vendor/lib/libchromatix_ov8858_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_common.so:system/vendor/lib/libchromatix_ov8865_q8v18a_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so:system/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_preview.so:system/vendor/lib/libchromatix_ov8865_q8v18a_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so:system/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so:system/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov9724_common.so:system/vendor/lib/libchromatix_ov9724_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov9724_default_video.so:system/vendor/lib/libchromatix_ov9724_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov9724_liveshot.so:system/vendor/lib/libchromatix_ov9724_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_ov9724_preview.so:system/vendor/lib/libchromatix_ov9724_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l1yx_common.so:system/vendor/lib/libchromatix_s5k3l1yx_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l1yx_default_video.so:system/vendor/lib/libchromatix_s5k3l1yx_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l1yx_liveshot.so:system/vendor/lib/libchromatix_s5k3l1yx_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l1yx_preview.so:system/vendor/lib/libchromatix_s5k3l1yx_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l1yx_snapshot.so:system/vendor/lib/libchromatix_s5k3l1yx_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l1yx_video_hd.so:system/vendor/lib/libchromatix_s5k3l1yx_video_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l1yx_zsl.so:system/vendor/lib/libchromatix_s5k3l1yx_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l2_common.so:system/vendor/lib/libchromatix_s5k3l2_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l2_default_video.so:system/vendor/lib/libchromatix_s5k3l2_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l2_default_video_wechat.so:system/vendor/lib/libchromatix_s5k3l2_default_video_wechat.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l2_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l2_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l2_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3l2_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l2_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3l2_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l2_liveshot_hd.so:system/vendor/lib/libchromatix_s5k3l2_liveshot_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l2_liveshot.so:system/vendor/lib/libchromatix_s5k3l2_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l2_lowlight.so:system/vendor/lib/libchromatix_s5k3l2_lowlight.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l2_preview_hd.so:system/vendor/lib/libchromatix_s5k3l2_preview_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l2_preview.so:system/vendor/lib/libchromatix_s5k3l2_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l2_snapshot_hd.so:system/vendor/lib/libchromatix_s5k3l2_snapshot_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l2_snapshot.so:system/vendor/lib/libchromatix_s5k3l2_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l2_snapshot_wechat.so:system/vendor/lib/libchromatix_s5k3l2_snapshot_wechat.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l2_video_hd.so:system/vendor/lib/libchromatix_s5k3l2_video_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3l2_zsl.so:system/vendor/lib/libchromatix_s5k3l2_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3m2xm_common.so:system/vendor/lib/libchromatix_s5k3m2xm_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3m2xm_default_video.so:system/vendor/lib/libchromatix_s5k3m2xm_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3m2xm_hfr_120.so:system/vendor/lib/libchromatix_s5k3m2xm_hfr_120.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3m2xm_hfr_60.so:system/vendor/lib/libchromatix_s5k3m2xm_hfr_60.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3m2xm_hfr_90.so:system/vendor/lib/libchromatix_s5k3m2xm_hfr_90.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3m2xm_liveshot.so:system/vendor/lib/libchromatix_s5k3m2xm_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3m2xm_preview.so:system/vendor/lib/libchromatix_s5k3m2xm_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k3m2xm_snapshot.so:system/vendor/lib/libchromatix_s5k3m2xm_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_common.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_default_video.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_120fps.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_60fps.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_90fps.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_liveshot.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_preview.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_snapshot.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_video_hd.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_video_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_zsl.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k4h5_common.so:system/vendor/lib/libchromatix_s5k4h5_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k4h5_default_video.so:system/vendor/lib/libchromatix_s5k4h5_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k4h5_hfr_120fps.so:system/vendor/lib/libchromatix_s5k4h5_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k4h5_hfr_60fps.so:system/vendor/lib/libchromatix_s5k4h5_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k4h5_hfr_90fps.so:system/vendor/lib/libchromatix_s5k4h5_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k4h5_liveshot_hd.so:system/vendor/lib/libchromatix_s5k4h5_liveshot_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k4h5_liveshot.so:system/vendor/lib/libchromatix_s5k4h5_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k4h5_preview_hd.so:system/vendor/lib/libchromatix_s5k4h5_preview_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k4h5_preview.so:system/vendor/lib/libchromatix_s5k4h5_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k4h5_snapshot_hd.so:system/vendor/lib/libchromatix_s5k4h5_snapshot_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k4h5_snapshot.so:system/vendor/lib/libchromatix_s5k4h5_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k4h5_video_hd.so:system/vendor/lib/libchromatix_s5k4h5_video_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k4h5_zsl.so:system/vendor/lib/libchromatix_s5k4h5_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k5e8_common.so:system/vendor/lib/libchromatix_s5k5e8_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k5e8_default_video.so:system/vendor/lib/libchromatix_s5k5e8_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k5e8_default_video_wechat.so:system/vendor/lib/libchromatix_s5k5e8_default_video_wechat.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k5e8_hfr_120fps.so:system/vendor/lib/libchromatix_s5k5e8_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k5e8_hfr_60fps.so:system/vendor/lib/libchromatix_s5k5e8_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k5e8_hfr_90fps.so:system/vendor/lib/libchromatix_s5k5e8_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k5e8_liveshot_hd.so:system/vendor/lib/libchromatix_s5k5e8_liveshot_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k5e8_liveshot.so:system/vendor/lib/libchromatix_s5k5e8_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k5e8_preview_hd.so:system/vendor/lib/libchromatix_s5k5e8_preview_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k5e8_preview.so:system/vendor/lib/libchromatix_s5k5e8_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k5e8_snapshot_hd.so:system/vendor/lib/libchromatix_s5k5e8_snapshot_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k5e8_snapshot.so:system/vendor/lib/libchromatix_s5k5e8_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k5e8_snapshot_wechat.so:system/vendor/lib/libchromatix_s5k5e8_snapshot_wechat.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k5e8_video_hd.so:system/vendor/lib/libchromatix_s5k5e8_video_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_s5k5e8_zsl.so:system/vendor/lib/libchromatix_s5k5e8_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libdataitems.so:system/vendor/lib/libdataitems.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libHevcSwDecoder.so:system/vendor/lib/libHevcSwDecoder.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/liblocationservice_glue.so:system/vendor/lib/liblocationservice_glue.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libloc_ext.so:system/vendor/lib/libloc_ext.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera2_q3a_core.so:system/vendor/lib/libmmcamera2_q3a_core.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_dw9761b_eeprom.so:system/vendor/lib/libmmcamera_dw9761b_eeprom.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_gc0310.so:system/vendor/lib/libmmcamera_gc0310.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_imx132.so:system/vendor/lib/libmmcamera_imx132.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_imx134.so:system/vendor/lib/libmmcamera_imx134.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_imx135.so:system/vendor/lib/libmmcamera_imx135.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_imx214.so:system/vendor/lib/libmmcamera_imx214.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so:system/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov13850_q13v06k.so:system/vendor/lib/libmmcamera_ov13850_q13v06k.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov13850.so:system/vendor/lib/libmmcamera_ov13850.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov16825.so:system/vendor/lib/libmmcamera_ov16825.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov2680_5987fhq.so:system/vendor/lib/libmmcamera_ov2680_5987fhq.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov2680_cht852b.so:system/vendor/lib/libmmcamera_ov2680_cht852b.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov2680.so:system/vendor/lib/libmmcamera_ov2680.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov2680_zs2p80f1.so:system/vendor/lib/libmmcamera_ov2680_zs2p80f1.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov2720.so:system/vendor/lib/libmmcamera_ov2720.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov5645.so:system/vendor/lib/libmmcamera_ov5645.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov5648_oty5f03.so:system/vendor/lib/libmmcamera_ov5648_oty5f03.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov5648_p5v18g.so:system/vendor/lib/libmmcamera_ov5648_p5v18g.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov5648_q5v22e.so:system/vendor/lib/libmmcamera_ov5648_q5v22e.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov5670_30010a3.so:system/vendor/lib/libmmcamera_ov5670_30010a3.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov5670_q5v41b.so:system/vendor/lib/libmmcamera_ov5670_q5v41b.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov5670_qc700.so:system/vendor/lib/libmmcamera_ov5670_qc700.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov7695.so:system/vendor/lib/libmmcamera_ov7695.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov8825.so:system/vendor/lib/libmmcamera_ov8825.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov8858_q8v19w_30.so:system/vendor/lib/libmmcamera_ov8858_q8v19w_30.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov8858_q8v19w.so:system/vendor/lib/libmmcamera_ov8858_q8v19w.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov8858.so:system/vendor/lib/libmmcamera_ov8858.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov8865_q8v18a.so:system/vendor/lib/libmmcamera_ov8865_q8v18a.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_ov9724.so:system/vendor/lib/libmmcamera_ov9724.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_pdafcamif.so:system/vendor/lib/libmmcamera_pdafcamif.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_pdaf.so:system/vendor/lib/libmmcamera_pdaf.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_qtech_gt24c16_eeprom.so:system/vendor/lib/libmmcamera_qtech_gt24c16_eeprom.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_s5k3l1yx.so:system/vendor/lib/libmmcamera_s5k3l1yx.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_s5k3l2.so:system/vendor/lib/libmmcamera_s5k3l2.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_s5k3m2xm.so:system/vendor/lib/libmmcamera_s5k3m2xm.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_S5K4E1_13P1BA.so:system/vendor/lib/libmmcamera_S5K4E1_13P1BA.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_s5k4h5_8916.so:system/vendor/lib/libmmcamera_s5k4h5_8916.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_s5k5e8.so:system/vendor/lib/libmmcamera_s5k5e8.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so:system/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so:system/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so:system/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so:system/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so:system/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_sonyimx135_eeprom.so:system/vendor/lib/libmmcamera_sonyimx135_eeprom.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_sp1628.so:system/vendor/lib/libmmcamera_sp1628.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_sunny_ov13850_eeprom.so:system/vendor/lib/libmmcamera_sunny_ov13850_eeprom.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_sunny_ov8858_q8v19w_eeprom.so:system/vendor/lib/libmmcamera_sunny_ov8858_q8v19w_eeprom.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:system/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_sunny_q13v04b_eeprom.so:system/vendor/lib/libmmcamera_sunny_q13v04b_eeprom.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_sunny_q13v06k_eeprom.so:system/vendor/lib/libmmcamera_sunny_q13v06k_eeprom.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_sunny_q5v22e_eeprom.so:system/vendor/lib/libmmcamera_sunny_q5v22e_eeprom.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_sunny_q5v41b_eeprom.so:system/vendor/lib/libmmcamera_sunny_q5v41b_eeprom.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_sunrise_pc0fe_eeprom.so:system/vendor/lib/libmmcamera_sunrise_pc0fe_eeprom.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_truly_cm7700_eeprom.so:system/vendor/lib/libmmcamera_truly_cm7700_eeprom.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libmpbase.so:system/vendor/lib/libmpbase.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libxt_native.so:system/vendor/lib/libxt_native.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/asus/ASUS_X00AD_2/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so

PRODUCT_PACKAGES += \
    libtime_genoff \
    shutdownlistener \
    TimeService \
    com.qualcomm.location \
    qcrilmsgtunnel \
    com.qti.location.sdk \
    imscmlibrary \
    qcnvitems \
    qcrilhook
